<?php

namespace AppBundle\Repository;

/**
 * DatosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DatosRepository extends \Doctrine\ORM\EntityRepository
{
}
